### ISSUE TITLE
Invalid Auth Token when browsing stations

### ISSUE THREAD

**Issue by jcass77** [rectalogic/mopidy-pandora#42]
Browsing stations sometimes does not work after a long period of inactivity. Instead of the list of stations appearing, and empty list is displayed.

This could either be due to:

- the fact that ```user.getStationList``` and ```station.getGenreStations``` is run in parallel in different threads and that some sort of race condition occurs
- there's a server side issue causing ```1001: An unexpected error occurred```, and the first few requests fail as a result.

The issue is fairly rare and just clicking on the last played track in the tracklist will re-authenticate correctly and fill the caches with the station list information.

It might be necessary to add a ```threading.Lock()``` to ensure that only one process re-authenticates at a time, or to catch the 1001-code exceptions with some sort of special retry logic.

Full stack trace below:
```
2016-01-21 22:02:51,714 - INFO     TRANSPORT: 
METHOD: user.getStationList
PARAMS: {'user_id': u'175482532', 'auth_token': u'VICRE1lhaAOhdqsswBEnhWIfVG0Vgr3hpD2phwZaC3JRwk6HH7GfHL6Q==', 'partner_id': u'42', 'method': 'user.getStationList'}
DATA: {'userAuthToken': u'VICRE1lhaAOhdqsswBEnhWIfVG0Vgr3hpD2phwZaC3JRwk6HH7GfHL6Q==', 'syncTime': 1453406567, 'includeStationArtUrl': True}
URL: http://tuner.pandora.com/services/json/
2016-01-21 22:02:51,719 - INFO     TRANSPORT: 
METHOD: station.getGenreStations
PARAMS: {'user_id': u'175482532', 'auth_token': u'VICRE1lhaAOhdqsswBEnhWIfVG0Vgr3hpD2phwZaC3JRwk6HH7GfHL6Q==', 'partner_id': u'42', 'method': 'station.getGenreStations'}
DATA: {'userAuthToken': u'VICRE1lhaAOhdqsswBEnhWIfVG0Vgr3hpD2phwZaC3JRwk6HH7GfHL6Q==', 'syncTime': 1453406567}
URL: http://tuner.pandora.com/services/json/
2016-01-21 22:02:51,753 - INFO     Resetting dropped connection: tuner.pandora.com
2016-01-21 22:02:51,758 - INFO     Starting new HTTP connection (3): tuner.pandora.com
2016-01-21 22:02:52,514 - INFO     TRANSPORT: 
RESULT: {"stat":"fail","message":"An unexpected error occurred","code":1001}

2016-01-21 22:02:52,518 - INFO     TRANSPORT: 
METHOD: auth.partnerLogin
PARAMS: {'user_id': None, 'auth_token': None, 'partner_id': None, 'method': 'auth.partnerLogin'}
DATA: {'username': u'android', 'userAuthToken': None, 'deviceModel': u'android-generic', 'syncTime': None, 'version': '5', 'password': u'AC7IBG09A3DTSYM4R41UJWL07VLN8JI7'}
URL: https://tuner.pandora.com/services/json/
2016-01-21 22:02:52,544 - INFO     Resetting dropped connection: tuner.pandora.com
2016-01-21 22:02:52,550 - INFO     TRANSPORT: 
RESULT: {"stat":"fail","message":"An unexpected error occurred","code":1001}

2016-01-21 22:02:52,554 - INFO     TRANSPORT: 
METHOD: auth.partnerLogin
PARAMS: {'user_id': None, 'auth_token': None, 'partner_id': None, 'method': 'auth.partnerLogin'}
DATA: {'username': u'android', 'userAuthToken': None, 'deviceModel': u'android-generic', 'syncTime': None, 'version': '5', 'password': u'AC7IBG09A3DTSYM4R41UJWL07VLN8JI7'}
URL: https://tuner.pandora.com/services/json/
2016-01-21 22:02:52,594 - INFO     Starting new HTTPS connection (4): tuner.pandora.com
2016-01-21 22:02:54,863 - INFO     TRANSPORT: 
RESULT: {"stat":"ok","result":{"stationSkipLimit":6,"partnerId":"42","partnerAuthToken":"VAI+vKUfyXtPc0fIJakAaeb15HA63B1nFA","syncTime":"f965207c45b03fbe59cac40964739354","deviceProperties":{"optionalFeatures":{"optionalFeature":[{"feature":"useAudioProxy2","enabled":"false","platformVersionRange":{"low":"4.0","high":"5.0.0"},"productVersionRange":{"low":"1.6","high":"*"}}]},"adRefreshInterval":4,"videoAdUniqueInterval":0,"videoAdRefreshInterval":870,"videoAdStartInterval":180,"ooyala":{"streamingPercentage":0,"streamingWhitelist":[534051315],"videoAdBufferRetryCount":3,"videoAdLoadingTimeout":2,"videoAdPlayTimeout":8}},"stationSkipUnit":"hour"}}

2016-01-21 22:02:54,869 - INFO     TRANSPORT: 
RESULT: {"stat":"ok","result":{"stationSkipLimit":6,"partnerId":"42","partnerAuthToken":"VAI+vKUfyXtPfOIZIgqV3pK15HA63B1nFA","syncTime":"78a1790b9f3995cd59cac40964739354","deviceProperties":{"optionalFeatures":{"optionalFeature":[{"feature":"useAudioProxy2","enabled":"false","platformVersionRange":{"low":"4.0","high":"5.0.0"},"productVersionRange":{"low":"1.6","high":"*"}}]},"adRefreshInterval":4,"videoAdUniqueInterval":0,"videoAdRefreshInterval":870,"videoAdStartInterval":180,"ooyala":{"streamingPercentage":0,"streamingWhitelist":[534051315],"videoAdBufferRetryCount":3,"videoAdLoadingTimeout":2,"videoAdPlayTimeout":8}},"stationSkipUnit":"hour"}}

2016-01-21 22:02:54,875 - INFO     TRANSPORT: 
METHOD: auth.userLogin
PARAMS: {'user_id': None, 'auth_token': u'VAI+vKUfyXtPfOIZIgqV3pK15HA63B1nFA', 'partner_id': u'42', 'method': 'auth.userLogin'}
DATA: {'username': u'name', 'includePandoraOneInfo': True, 'password': u'pwd', 'partnerAuthToken': u'VAI+vKUfyXtPfOIZIgqV3pK15HA63B1nFA', 'syncTime': 1453406569, 'includeSubscriptionExpiration': True, 'loginType': 'user', 'userAuthToken': None, 'xplatformAdCapable': True, 'returnCapped': True, 'includeAdAttributes': True, 'includeAdvertiserAttributes': True}
URL: https://tuner.pandora.com/services/json/
2016-01-21 22:02:54,879 - INFO     TRANSPORT: 
METHOD: auth.userLogin
PARAMS: {'user_id': None, 'auth_token': u'VAI+vKUfyXtPfOIZIgqV3pK15HA63B1nFA', 'partner_id': u'42', 'method': 'auth.userLogin'}
DATA: {'username': u'name', 'includePandoraOneInfo': True, 'password': u'pwd', 'partnerAuthToken': u'VAI+vKUfyXtPc0fIJakAaeb15HA63B1nFA', 'syncTime': 1453406569, 'includeSubscriptionExpiration': True, 'loginType': 'user', 'userAuthToken': None, 'xplatformAdCapable': True, 'returnCapped': True, 'includeAdAttributes': True, 'includeAdvertiserAttributes': True}
URL: https://tuner.pandora.com/services/json/
2016-01-21 22:02:55,312 - INFO     TRANSPORT: 
RESULT: {"stat":"fail","message":"An unexpected error occurred","code":1001}

2016-01-21 22:02:55,317 - ERROR    PandoraBackend backend caused an exception.
Traceback (most recent call last):
  File "/var/lib/git/mopidy/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/var/lib/git/mopidy/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/local/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/local/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/var/lib/git/mopidy-pandora/mopidy_pandora/library.py", line 40, in browse
    return self._browse_stations()
  File "/var/lib/git/mopidy-pandora/mopidy_pandora/library.py", line 139, in _browse_stations
    stations = self.backend.api.get_station_list()
  File "/var/lib/git/mopidy-pandora/mopidy_pandora/client.py", line 57, in get_station_list
    station_list = super(MopidyAPIClient, self).get_station_list()
  File "/var/lib/git/pydora/pandora/client.py", line 125, in get_station_list
    includeStationArtUrl=True))
  File "/var/lib/git/pydora/pandora/client.py", line 109, in __call__
    self._authenticate()
  File "/var/lib/git/pydora/pandora/client.py", line 86, in _authenticate
    xplatformAdCapable=True)
  File "/var/lib/git/pydora/pandora/transport.py", line 50, in function
    return func(*args, **kwargs)
  File "/var/lib/git/pydora/pandora/transport.py", line 243, in __call__
    return self._parse_response(result)
  File "/var/lib/git/pydora/pandora/transport.py", line 225, in _parse_response
    raise PandoraException.from_code(result["code"], result["message"])
InvalidAuthToken: Invalid Auth Token
2016-01-21 22:02:55,407 - INFO     TRANSPORT: 
RESULT: {"stat":"ok","result":{"hasAudioAds":true,"minimumAdRefreshInterval":5,"userAuthToken":"VIDQ8w2fcJ2Gm7vIDQ7vla8U877HgKCDPef8rMUJp4LtwDTr+EUrusag==","userId":"175482532","username":"uname","canListen":true,"isCapped":false,"promotedStationsPrefetchExpirationSeconds":14400,"listeningTimeoutAlertMsgUri":"/mobile/still_listening.vm","zeroVolumeNumMutedTracks":1,"listeningTimeoutMinutes":"180","splashScreenAdUrl":"http://ad.doubleclick.net/adx/pand.android/prod.welcome;a10=1;a11=1;a11=12;a11=16;a11=17;a11=21;a11=23;a11=25;a11=4;a11=6;a12=28;a12=38;a12=39;a12=40;d1=6;d2=32;d3=48;d3=50;d3=53;d4=415;d4=433;d8=0;p=1;p=4;p=8;t4=160;t4=208;t4=218;t4=220;t4=221;t4=225;t4=226;t4=227;t4=229;t4=233;t4=236;t4=256;t4=274;t4=275;t4=276;t4=281;mdid=9f058025faaef7993be67cfc3596c8cd;msa=003;OS=;aa=0;ag=38;app=;bz=;clean=0;co=06037;con=;dma=803;et=0;fam=-1;gnd=1;hhi=1;hisp=0;hours=0;iat=1;l=27oiry5k23232pxkduq56o55suf2ymd56cwjd3q;mc=0;model=;tablet=0;mp=1;st=CA;uq=9f058025faaef7993be67cfc3596c8cd;vx=;vxc=;zip=90210;sz=320x50;ord=__CACHEBUST__","userPPID":"9f058025faaef7993be67cfc3596c8cd","promotedStationsRecommendationFallback":true,"eligibleForPromotedStations":true,"userProfileUrl":"https://www.pandora.com/login?auth_token=VIDQ8w2fcJ2Gm7vIDQ7vla8U877HgKCDPef8rMUJp4LtwDTr%2BEUrusag%3D%3D&target=%2Fprofile%2Fpandora.dev2","maxStationsAllowed":100,"videoAdUrl":"http://ad.doubleclick.net/pfadx/pand.android/prod.nowplaying;a10=1;a11=1;a11=12;a11=16;a11=17;a11=21;a11=23;a11=25;a11=4;a11=6;a12=28;a12=38;a12=39;a12=40;d1=6;d2=32;d3=48;d3=50;d3=53;d4=415;d4=433;d8=0;p=1;p=4;p=8;t4=160;t4=208;t4=218;t4=220;t4=221;t4=225;t4=226;t4=227;t4=229;t4=233;t4=236;t4=256;t4=274;t4=275;t4=276;t4=281;mdid=9f058025faaef7993be67cfc3596c8cd;msa=003;OS=;aa=0;ag=38;app=;bz=;clean=0;co=06037;con=;dma=803;et=0;fam=-1;gnd=1;hhi=1;hisp=0;hours=0;index=__INDEX__;l=r6d4lrx4bdxzssyes7batwqg4n34kcvezidyhdq;mc=0;model=;tablet=0;mp=1;st=CA;uq=9f058025faaef7993be67cfc3596c8cd;vx=;zip=90210;sz=442x188;ord=__CACHEBUST__","stationCreationAdUrl":"http://ad.doubleclick.net/adx/pand.android/prod.createstation;a10=1;a11=1;a11=12;a11=16;a11=17;a11=21;a11=23;a11=25;a11=4;a11=6;a12=28;a12=38;a12=39;a12=40;d1=6;d2=32;d3=48;d3=50;d3=53;d4=415;d4=433;d8=0;p=1;p=4;p=8;t4=160;t4=208;t4=218;t4=220;t4=221;t4=225;t4=226;t4=227;t4=229;t4=233;t4=236;t4=256;t4=274;t4=275;t4=276;t4=281;mdid=9f058025faaef7993be67cfc3596c8cd;msa=003;OS=;aa=0;ag=38;app=;bz=;clean=0;co=06037;con=;dma=803;et=0;fam=-1;genre=0;gnd=1;hhi=1;hisp=0;l=krizdbpuhvsf355svqp4fjq2wpfbntp3gtx33pi;mc=0;model=;tablet=0;mp=1;st=CA;uq=9f058025faaef7993be67cfc3596c8cd;vx=;zip=90210;tile=1;sz=320x50;ord=__CACHEBUST__","subscriptionHasExpired":false,"zeroVolumeAutoPauseEnabledFlag":true}}

2016-01-21 22:02:55,412 - INFO     TRANSPORT: 
METHOD: station.getGenreStations
PARAMS: {'user_id': u'175482532', 'auth_token': u'VIDQ8w2fcJ2Gm7vIDQ7vla8U877HgKCDPef8rMUJp4LtwDTr+EUrusag==', 'partner_id': u'42', 'method': 'station.getGenreStations'}
DATA: {'userAuthToken': u'VIDQ8w2fcJ2Gm7vIDQ7vla8U877HgKCDPef8rMUJp4LtwDTr+EUrusag==', 'syncTime': 1453406570}
URL: http://tuner.pandora.com/services/json/
```

**Comment by jcass77** [comment]
I haven't encountered this since https://github.com/rectalogic/mopidy-pandora/commit/9507c40d2eb73fc6773740ed576d1fef9f4dd8c7 was committed. I think removing the threading might have solved this issue.

I'm going to close this now - please re-open if necessary.
