### ISSUE TITLE
Got un-handled exception from PandoraBackend

### ISSUE THREAD

**Issue by srb37** [rectalogic/mopidy-pandora#66]
I receive the following error on a fresh Raspberry Pi install: 
`ERROR    Got un-handled exception from PandoraBackend
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 237, in _actor_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 386, in start_backends
    config=config, audio=audio).proxy()
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 94, in start
    obj = cls(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_pandora/backend.py", line 41, in __init__
    self.library = PandoraLibraryProvider(backend=self, sort_order=self.config.get('sort_order'))
  File "/usr/local/lib/python2.7/dist-packages/mopidy_pandora/library.py", line 36, in __init__
    self.pandora_station_cache = LRUCache(maxsize=5, missing=self.get_station_cache_item)
TypeError: __init__() got an unexpected keyword argument 'missing'`

**Comment by jcass77** [comment]
Thanks for reporting the issue, I suspected that it had to do with a change in cachetools but did not have time to confirm over the weekend.

I'll see about getting a fix in - for now suggest that everyone just pin cachetools to version 2.1.0.
